title: Hello, world! I'm Jude Dzevela Kong.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url:http://judekong.ca "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Jude Dzevela Kong # add your name
author-img: profile.jpg # add your photo
about-author: I am an NSERC Postdoctoral Fellow working with Professor Simon Levin. I obtained my Ph.D. alongside an embidded certificate in Data Sciences from the University of Alberta. # add description
twitter:dzevela # add your Twitter handle
facebook:dzevela # add your Facebook handle
github: judekong # add your Github handle
linkedin:jude-dzevela-kong-1311b027 # add your Linkedin handle
email:dzevela85@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
